apiVersion: kuttl.dev/v1beta1
kind: TestSuite
startKIND: true
skipClusterDelete: false
skipDelete: true
namespace: default
kindConfig: kind.yaml
kindContext: stkbl-cntxt
artifactsDir: ./kuttl-test/artifacts/
testDirs:
  - kuttl-test/tests/
parallel: 1
timeout: 180
