apiVersion: kuttl.dev/v1beta1
kind: TestSuite
commands:
  - command: helm repo add stackable-dev https://repo.stackable.tech/repository/helm-dev
  - command: helm upgrade spark-operator stackable-dev/spark-operator --version="0.5.0-nightly" --install

startKIND: false
skipClusterDelete: true
skipDelete: true
namespace: default
kindConfig: kind.yaml
kindContext: stkbl-cntxt
artifactsDir: ./kuttl-test/artifacts/
testDirs:
  - kuttl-test/tests/
parallel: 1
timeout: 120
