---
apiVersion: t2.stackable.tech/v1
kind: Infra
template: hcloud-centos-8
metadata:
  name: functional-platform-tests
  description: "Cluster for functional-platform tests (Hetzner Cloud / CentOS 8)"
domain: stackable.test
publicKeys: []
spec:
  k8sVersion: "$K8S_VERSION"
  wireguard: false
  versions:
    spark-operator: "$SPARK_OPERATOR_VERSION"
    hdfs-operator: "$HDFS_OPERATOR_VERSION"
    zookeeper-operator: "$ZOOKEEPER_OPERATOR_VERSION"
    hbase-operator: "$HBASE_OPERATOR_VERSION"
    secret-operator: "$SECRET_OPERATOR_VERSION"
    commons-operator: "$COMMONS_OPERATOR_VERSION"
  nodes:
    main:
      numberOfNodes: 3
