---
apiVersion: hbase.stackable.tech/v1alpha1
kind: HbaseCluster
metadata:
  name: fkt-test-hbase
spec:
  version: {{ test_scenario['values']['hbase'] }}
  hdfsConfigMapName: hdfs-namenode-default
  zookeeperConfigMapName: hbase-znode
  config:
    hbaseRootdir: /hbase
  masters:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 1
  regionServers:
    roleGroups:
      default:
        selector:
          matchLabels:
            kubernetes.io/os: linux
        replicas: 2