---
apiVersion: kuttl.dev/v1beta1
kind: TestAssert
timeout: 800
metadata:
  name: fct-test-spark-hdfs
commands:
  - script: ./test-jobs-root/spark-hdfs/sparkPreparation.sh $NAMESPACE
  - command: ./kubeassert/kubectl-assert spark-hdfs-file-exist processedTestdata.txt -v