---
apiVersion: hive.stackable.tech/v1alpha1
kind: HiveCluster
metadata:
  name: simple-postgres
spec:
  version: 2.3.9
  metastore:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - key: stackable/role
              operator: In
              values:
                - manager-role
        replicas: 1
        config:
          javaHome: /usr/lib/jvm/java-11-openjdk-amd64/
          metricsPort: 11111
          database:
            connString: jdbc:postgresql://manager-1.local:5432/metastore
            user: hive
            password: hivepass
            dbType: postgres
          warehouseDir: hdfs://master-1.local:9000/warehouse
