---
apiVersion: kafka.stackable.tech/v1alpha1
kind: KafkaCluster
metadata:
  name: simple
spec:
  version:
    kafka_version: 2.8.0
  zookeeperReference:
    namespace: default
    name: simple
  brokers:
    roleGroups:
      default:
        selector:
          matchLabels:
            stackable/role: stream-role
        replicas: 3
        config:
          logDirs: "/data/kafka/kafka-logs"
          metricsPort: 9606