---
apiVersion: spark.stackable.tech/v1alpha1
kind: SparkCluster
metadata:
  name: simple
spec:
  version: "3.0.1"
  config:
    logDir: "/data/spark/logs"
    enableMonitoring: true
  masters:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - key: stackable/role
              operator: In
              values:
                - master-role-1
        replicas: 1
        config:
          masterPort: 7078
          masterWebUiPort: 8081
  workers:
    roleGroups:
      2core2g:
        selector:
          matchExpressions:
            - key: stackable/role
              operator: In
              values:
                - worker-role
        replicas: 3
        config:
          cores: 2
          memory: "2g"
          workerPort: 3031
          workerWebUiPort: 8083
  historyServers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - key: stackable/role
              operator: In
              values:
                - utility-role
        replicas: 1
        config:
          historyWebUiPort: 18081
