---
apiVersion: zookeeper.stackable.tech/v1alpha1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    roleGroups:
      default:
        selector:
          matchExpressions:
            - key: stackable/role
              operator: In
              values:
                - master-role-1
                - master-role-2
        replicas: 3
        config:
          adminPort: 12000
          metricsPort: 9505
          dataDir: /data/zookeeper